apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer
  namespace: default
spec:
  replicas: 9
  selector:
    matchLabels:
      app: load-balancer
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      containers:
        - name: load-balancer
          image: lordjoaosouza/requesting-k8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
